### PR TITLE
[press] Added link to OpenWISP Monitoring GSoC '20 blog

### PR DESCRIPTION
**Pull request by nepython**
@nemesisdesign, wasn't sure of the order at which the link should be added (so added in the end for now).
Also, if you have any better title to suggest please feel free to do so :)

### CODE REVIEW

**Review by nemesisdesign — APPROVED** [review]
It's fine, thanks!

@atb00ker @pandafy @rohithasrk @edoput @ritwickdsouza if you want you can add a link to your GSoC work here too, I think it's useful!

**Comment by atb00ker** [comment]
@nemesisdesign already marked it in my todo, will create a PR asap.

**Comment by pandafy** [comment]
I think it will be better to add a dedicated section for GSoC reports. :smile:

**Comment by atb00ker** [comment]
@pandafy Sounds good to me.
@What do you think @nemesisdesign ?

**Pull request merged**
