### PR TITLE
Values and goals documentation

### PR DESCRIPTION
**Pull request by HargovindArora**
I have added some lines here. @nemesisdesign Please have a look at it and suggest any changes or things that you want particularly to mention it here! :)

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@HargovindArora great work! Let me find the time to improve this PR before merging.
I will merge on my own branch, apply changes, and push when ready

**Comment by HargovindArora** [comment]
Sure sure. It's an important Document and we should make it a good one. @nemesisdesign ! :)

**Comment by nemesisdesign** [comment]
Merged manually, thank you very much @HargovindArora! Great work, you are encouraging me to put more effort! 👍

**Comment by HargovindArora** [comment]
You applied a lot of effort in redesigning this! Thank you! :) @nemesisdesign

**Pull request closed without merging**
