### PR TITLE
Fixing The Openwisp 2 Documentation 

### PR DESCRIPTION
**Pull request by MiHiR151203**
What If We Add More Video's That Guide New Users..

### CODE REVIEW

**Comment by MiHiR151203** [comment]
I Mean Video Tutorials

**Comment by MiHiR151203** [comment]
Adding More Languages..

**Comment by MiHiR151203** [comment]
Or adding translate option for particular Line

**Comment by xamfy** [comment]
Left you a message on gci task page

**Comment by MiHiR151203** [comment]
Adding More Languages or adding more video tutorials

**Comment by MiHiR151203** [comment]
can someone tell me that from which page I copied this contain please send me the link of that page.

**Comment by MiHiR151203** [comment]
Federico Sir told me that the pull request is copied means the content in this pull request is copied from another page. But it was my idea and I posted it before 15 days ago. So that's why I said that please send me the link from which page I copied this content.
I apologize if there's any grammar mistake from my end.

**Pull request closed without merging**
