### PR TITLE
Added \ To Skip The Character Limit

### PR DESCRIPTION
**Pull request by IAmAMissingColon**
Added The \ To Override The Limit Of Character's

### CODE REVIEW

**Comment by IAmAMissingColon** [comment]
What's Failing Now ?

**Comment by 2stacks** [comment]
If you look at the [Details](https://travis-ci.org/openwisp/openwisp2-docs/builds/606153300?utm_source=github_status&utm_medium=notification) for the build you'll see the error. 

>  Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines

Change the commit message to something like; 
[docs] Added \ To Skip The Character Limit

**Comment by IAmAMissingColon** [comment]
> If you look at the [Details](https://travis-ci.org/openwisp/openwisp2-docs/builds/606153300?utm_source=github_status&utm_medium=notification) for the build you'll see the error.
> 
> > Please read our guidelines at: http://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines
> 
> Change the commit message to something like;
> [docs] Added \ To Skip The Character Limit

Yeah! Ok Got It !

**Comment by IAmAMissingColon** [comment]
@atb00ker Thank You :smiley:

**Comment by IAmAMissingColon** [comment]
Mistakenly Added, Sorry :disappointed:

**Comment by IAmAMissingColon** [comment]
Added \ to dd command without it wasn't working properly :smile:

**Comment by 2stacks** [comment]
No worries please squash your commits so we can merge.

**Comment by 2stacks** [comment]
Thanks @IAmAMissingColon looks good now.

**Comment by IAmAMissingColon** [comment]
> Thanks @IAmAMissingColon looks good now.

My Pleasure. Sir!

**Comment by ppabcd** [comment]
Good job @IAmAMissingColon

**Comment by IAmAMissingColon** [comment]
@ppabcd Thank You :)

**Comment by IAmAMissingColon** [comment]
@atb00ker Thank You :)

**Pull request merged**
